export enum ACTION_TYPES {
    DATA_CARDS="@@CARDS/DATA_CARDS",
    SET_CARDS= "@@CARDS/SET_CARDS",
    ADD_CARD= "@@CARD/ADD_CARD",
    SUCCESS_ADDED_CARD= '@@CARD/SUCCESS_ADDED_CARD',
    DELETE_CARD= "@@CARD/DELETE_CARD",
    SUCCESS_DELETE_CARD= '@@CARD/SUCCESS_DELETE_CARD'
}